name: Beagle Backend Pull Request

on:
    push:
        branches:
            - master
    pull_request:
        paths:
            - 'backend/**'
            - 'common/**'
            - 'schema/kotlin/**'
            - 'Gemfile'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: Cache gradle dependences
                uses: actions/cache@v2
                env:
                    gradle-cache-key: gradle-cache
                    gradle-path: ~/.gradle
                with:
                    path: ${{ env.gradle-path }}
                    key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('backend/buildSrc/**') }}
            -   name: Cache sonar dependences
                uses: actions/cache@v2
                env:
                    sonar-cache-key: sonar-cache
                    sonar-path: ~/.sonar
                 with:
                    path: ${{ env.sonar-path }}
                    key: ${{ runner.os }}-build-${{ env.sonar-cache-key }}-${{ hashFiles('backend/buildSrc/**') }}                                       
            -   name: Run pr check
                env:
                    GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: bundle exec fastlane backend pull_request_verification
